# Workflow recipe from https://github.com/actions-rs/meta/blob/master/recipes/msrv.md
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  RUSTFLAGS: -Dwarnings
  # change manually in matrix
  rust_min: 1.65.0

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - 1.65.0
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo check
      - run: cargo check --features "log"
      - run: cargo check --features "tracing"
      - run: cargo check --all-features

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - 1.65.0
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test
      - run: cargo test --features "log"
      - run: cargo test --features "tracing"
      - run: cargo test --all-features

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.rust_min }}
          components: clippy
      - run: cargo clippy --all-features

  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.rust_min }}
          components: rustfmt
      - run: cargo fmt -- --check
